# 作業 : (Kaggle)鐵達尼生存預測
https://www.kaggle.com/c/titanic

# [作業目標]
- 試著模仿範例寫法, 在鐵達尼生存預測中, 觀察標籤編碼與獨編碼熱的影響

# [作業重點]
- 回答在範例中的觀察結果
- 觀察標籤編碼與獨熱編碼, 在特徵數量 / 邏輯斯迴歸分數 / 邏輯斯迴歸時間上, 分別有什麼影響 (In[3], Out[3], In[4], Out[4])

# 作業1
* 觀察範例，在房價預測中調整標籤編碼(Label Encoder) / 獨熱編碼 (One Hot Encoder) 方式，  
對於線性迴歸以及梯度提升樹兩種模型，何者影響比較大?

In [2]:
# 做完特徵工程前的所有準備 (與前範例相同)
import pandas as pd
import numpy as np
import copy, time
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import LabelEncoder

data_path = 'data/'
df_train = pd.read_csv(data_path + 'titanic_train.csv')
df_test = pd.read_csv(data_path + 'titanic_test.csv')

train_Y = df_train['Survived']
ids = df_test['PassengerId']
df_train = df_train.drop(['PassengerId', 'Survived'] , axis=1)
df_test = df_test.drop(['PassengerId'] , axis=1)
df = pd.concat([df_train,df_test])
df.head()

,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [3]:
#只取類別值 (object) 型欄位, 存於 object_features 中
object_features = []
for dtype, feature in zip(df.dtypes, df.columns):
    if dtype == 'object':
        object_features.append(feature)
print(f'{len(object_features)} Numeric Features : {object_features}\n')

# 只留類別型欄位
df = df[object_features]
df = df.fillna('None')
train_num = train_Y.shape[0]
df.head()

5 Numeric Features : ['Name', 'Sex', 'Ticket', 'Cabin', 'Embarked']

,Name,Sex,Ticket,Cabin,Embarked
0,"Braund, Mr. Owen Harris",male,A/5 21171,None,S
1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,PC 17599,C85,C
2,"Heikkinen, Miss. Laina",female,STON/O2. 3101282,None,S
3,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,113803,C123,S
4,"Allen, Mr. William Henry",male,373450,None,S

# 作業2
* 鐵達尼號例題中，標籤編碼 / 獨熱編碼又分別對預測結果有何影響? (Hint : 參考今日範例)

Ans:獨熱編碼比較好一點點

In [9]:
# 標籤編碼 + 羅吉斯迴歸

"""
Your Code Here
"""

df_temp = pd.DataFrame()
for c in df.columns:
    df_temp[c] = LabelEncoder().fit_transform(df[c])
train_X = df_temp[:train_num]
estimator = LogisticRegression()
start = time.time()
print(f'shape : {train_X.shape}')
print(f'score : {cross_val_score(estimator, train_X, train_Y, cv=5).mean()}')
print(f'time : {time.time() - start} sec')
print(train_X)

shape : (891, 5)
score : 0.780004837244799
time : 0.05919146537780762 sec
     Name  Sex  Ticket  Cabin  Embarked
0     155    1     720    185         3
1     286    0     816    106         0
2     523    0     914    185         3
3     422    0      65     70         3
4      22    1     649    185         3
5     818    1     373    185         2
6     767    1     109    163         3
7     914    1     541    185         3
8     605    0     477    185         3
9     847    0     174    185         0
10   1067    0     839    184         3
11    133    0      50     62         3
12   1070    1     733    185         3
13     38    1     459    185         3
14   1221    0     566    185         3
15    533    0     204    185         3
16    995    1     659    185         2
17   1271    1     201    185         3
18   1217    0     417    185         3
19    760    0     243    185         0
20    423    1     182    185         3
21    112    1     203    143         3
22    778    0     379    185         2
23   1111    1      54     17         3
24    917    0     541    185         3
25     64    0     454    185         3
26    371    1     238    185         0
27    404    1     123     80         3
28    885    0     385    185         2
29   1186    1     499    185         3
..    ...  ...     ...    ...       ...
861   439    1     302    185         3
862  1164    0     112    121         3
863  1051    0     778    185         3
864   442    1     154    185         3
865   177    0     161    185         3
866   356    0     863    185         0
867  1013    1     807      9         3
868  1306    1     428    185         3
869   600    1     477    185         3
870    86    1     531    185         3
871   111    0      70    131         3
872   202    1     688     45         3
873  1213    1     419    185         3
874     7    0     789    185         0
875   839    0     261    185         0
876   474    1     691    185         3
877   959    1     495    185         3
878   670    1     500    185         3
879   975    0      75     90         0
880  1083    0     147    185         3
881   757    1     540    185         3
882   290    0     697    185         3
883    88    1     774    185         3
884  1157    1     891    185         3
885   997    0     659    185         2
886   811    1     130    185         3
887   464    0      18     40         3
888   607    0     923    185         3
889   113    1      11     77         0
890   338    1     642    185         2

[891 rows x 5 columns]

D:\Users\steve.yj.chu\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
D:\Users\steve.yj.chu\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
D:\Users\steve.yj.chu\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
D:\Users\steve.yj.chu\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
D:\Users\steve.yj.chu\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)

In [11]:
# 獨熱編碼 + 羅吉斯迴歸

"""
Your Code Here
"""
df_temp = pd.get_dummies(df)
train_X = df_temp[:train_num]
estimator = LogisticRegression()
start = time.time()
print(f'shape : {train_X.shape}')
print(f'score : {cross_val_score(estimator, train_X, train_Y, cv=5).mean()}')
print(f'time : {time.time() - start} sec')
print(train_X)

shape : (891, 2429)

D:\Users\steve.yj.chu\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
D:\Users\steve.yj.chu\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
D:\Users\steve.yj.chu\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
D:\Users\steve.yj.chu\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
D:\Users\steve.yj.chu\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)

score : 0.8013346043513216
time : 0.2176051139831543 sec
     Name_Abbing, Mr. Anthony  Name_Abbott, Master. Eugene Joseph  \
0                           0                                   0
1                           0                                   0
2                           0                                   0
3                           0                                   0
4                           0                                   0
5                           0                                   0
6                           0                                   0
7                           0                                   0
8                           0                                   0
9                           0                                   0
10                          0                                   0
11                          0                                   0
12                          0                                   0
13                          0                                   0
14                          0                                   0
15                          0                                   0
16                          0                                   0
17                          0                                   0
18                          0                                   0
19                          0                                   0
20                          0                                   0
21                          0                                   0
22                          0                                   0
23                          0                                   0
24                          0                                   0
25                          0                                   0
26                          0                                   0
27                          0                                   0
28                          0                                   0
29                          0                                   0
..                        ...                                 ...
861                         0                                   0
862                         0                                   0
863                         0                                   0
864                         0                                   0
865                         0                                   0
866                         0                                   0
867                         0                                   0
868                         0                                   0
869                         0                                   0
870                         0                                   0
871                         0                                   0
872                         0                                   0
873                         0                                   0
874                         0                                   0
875                         0                                   0
876                         0                                   0
877                         0                                   0
878                         0                                   0
879                         0                                   0
880                         0                                   0
881                         0                                   0
882                         0                                   0
883                         0                                   0
884                         0                                   0
885                         0                                   0
886                         0                                   0
887                         0                                   0
888                         0                                   0
889                         0                                   0
890                         0                                   0

     Name_Abbott, Mr. Rossmore Edward  Name_Abbott, Mrs. Stanton (Rosa Hunt)  \
0                                   0                                      0
1                                   0                                      0
2                                   0                                      0
3                                   0                                      0
4                                   0                                      0
5                                   0                                      0
6                                   0                                      0
7                                   0                                      0
8                                   0                                      0
9                                   0                                      0
10                                  0                                      0
11                                  0                                      0
12                                  0                                      0
13                                  0                                      0
14                                  0                                      0
15                                  0                                      0
16                                  0                                      0
17                                  0                                      0
18                                  0                                      0
19                                  0                                      0
20                                  0                                      0
21                                  0                                      0
22                                  0                                      0
23                                  0                                      0
24                                  0                                      0
25                                  0                                      0
26                                  0                                      0
27                                  0                                      0
28                                  0                                      0
29                                  0                                      0
..                                ...                                    ...
861                                 0                                      0
862                                 0                                      0
863                                 0                                      0
864                                 0                                      0
865                                 0                                      0
866                                 0                                      0
867                                 0                                      0
868                                 0                                      0
869                                 0                                      0
870                                 0                                      0
871                                 0                                      0
872                                 0                                      0
873                                 0                                      0
874                                 0                                      0
875                                 0                                      0
876                                 0                                      0
877                                 0                                      0
878                                 0                                      0
879                                 0                                      0
880                                 0                                      0
881                                 0                                      0
882                                 0                                      0
883                                 0                                      0
884                                 0                                      0
885                                 0                                      0
886                                 0                                      0
887                                 0                                      0
888                                 0                                      0
889                                 0                                      0
890                                 0                                      0

     Name_Abelseth, Miss. Karen Marie  Name_Abelseth, Mr. Olaus Jorgensen  \
0                                   0                                   0
1                                   0                                   0
2                                   0                                   0
3                                   0                                   0
4                                   0                                   0
5                                   0                                   0
6                                   0                                   0
7                                   0                                   0
8                                   0                                   0
9                                   0                                   0
10                                  0                                   0
11                                  0                                   0
12                                  0                                   0
13                                  0                                   0
14                                  0                                   0
15                                  0                                   0
16                                  0                                   0
17                                  0                                   0
18                                  0                                   0
19                                  0                                   0
20                                  0                                   0
21                                  0                                   0
22                                  0                                   0
23                                  0                                   0
24                                  0                                   0
25                                  0                                   0
26                                  0                                   0
27                                  0                                   0
28                                  0                                   0
29                                  0                                   0
..                                ...                                 ...
861                                 0                                   0
862                                 0                                   0
863                                 0                                   0
864                                 0                                   0
865                                 0                                   0
866                                 0                                   0
867                                 0                                   0
868                                 0                                   0
869                                 0                                   0
870                                 0                                   0
871                                 0                                   0
872                                 0                                   0
873                                 0                                   0
874                                 0                                   0
875                                 0                                   0
876                                 0                                   0
877                                 0                                   0
878                                 0                                   0
879                                 0                                   0
880                                 0                                   0
881                                 0                                   0
882                                 0                                   0
883                                 0                                   0
884                                 0                                   0
885                                 0                                   0
886                                 0                                   0
887                                 0                                   0
888                                 0                                   0
889                                 0                                   0
890                                 0                                   0

     Name_Abelson, Mr. Samuel  Name_Abelson, Mrs. Samuel (Hannah Wizosky)  \
0                           0                                           0
1                           0                                           0
2                           0                                           0
3                           0                                           0
4                           0                                           0
5                           0                                           0
6                           0                                           0
7                           0                                           0
8                           0                                           0
9                           0                                           0
10                          0                                           0
11                          0                                           0
12                          0                                           0
13                          0                                           0
14                          0                                           0
15                          0                                           0
16                          0                                           0
17                          0                                           0
18                          0                                           0
19                          0                                           0
20                          0                                           0
21                          0                                           0
22                          0                                           0
23                          0                                           0
24                          0                                           0
25                          0                                           0
26                          0                                           0
27                          0                                           0
28                          0                                           0
29                          0                                           0
..                        ...                                         ...
861                         0                                           0
862                         0                                           0
863                         0                                           0
864                         0                                           0
865                         0                                           0
866                         0                                           0
867                         0                                           0
868                         0                                           0
869                         0                                           0
870                         0                                           0
871                         0                                           0
872                         0                                           0
873                         0                                           0
874                         0                                           1
875                         0                                           0
876                         0                                           0
877                         0                                           0
878                         0                                           0
879                         0                                           0
880                         0                                           0
881                         0                                           0
882                         0                                           0
883                         0                                           0
884                         0                                           0
885                         0                                           0
886                         0                                           0
887                         0                                           0
888                         0                                           0
889                         0                                           0
890                         0                                           0

     Name_Abrahamsson, Mr. Abraham August Johannes  \
0                                                0
1                                                0
2                                                0
3                                                0
4                                                0
5                                                0
6                                                0
7                                                0
8                                                0
9                                                0
10                                               0
11                                               0
12                                               0
13                                               0
14                                               0
15                                               0
16                                               0
17                                               0
18                                               0
19                                               0
20                                               0
21                                               0
22                                               0
23                                               0
24                                               0
25                                               0
26                                               0
27                                               0
28                                               0
29                                               0
..                                             ...
861                                              0
862                                              0
863                                              0
864                                              0